services:
  cloudflared:
    container_name: cloudflared
    environment:
      - PORT=53
    image: visibilityspots/cloudflared:latest
    networks:
      default:
        ipv4_address: 10.1.1.10
    restart: unless-stopped
  pihole:
    container_name: pihole
    environment:
      - ServerIP=10.0.0.10
      - PIHOLE_DNS_=10.1.1.10
      - DNSMASQ_LISTENING=all
      - TZ=Asia/Kolkata
      - WEBPASSWORD=${WEBPASSWORD}
    hostname: pihole
    image: pihole/pihole:latest
    networks:
      - default
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '67:67/udp'
      - '80:80/tcp'
      - '443:443/tcp'
    restart: unless-stopped
    volumes:
      - ./config/pihole:/etc/pihole
      - ./config/dnsmasq:/etc/dnsmasq.d

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.1.0/28
    name: dns