services:
  jellyfin:
    container_name: jellyfin
    depends_on:
      - rclone
    environment:
      - PUID=1000
      - PGID=1000
      - TZ='Asia/Kolkata'
      - JELLYFIN_PublishedServerUrl=pi
    image: linuxserver/jellyfin
    volumes:
      - /mnt/external/jellyfin:/config
      - /mnt/external/drive:/media
      - /opt/vc/lib:/opt/vc/lib
    ports:
      - "8096:8096"
      - "8920:8920"
      - "7359:7359/udp"
      - "1900:1900/udp"
    devices:
      - /dev/vcsm-cma:/dev/vcsm
      - /dev/vchiq:/dev/vchiq
      - /dev/video10:/dev/video10
      - /dev/video11:/dev/video11
      - /dev/video12:/dev/video12
    restart: unless-stopped
  rclone:
    cap_add:
      - SYS_ADMIN
    command: "mount Drive: /mnt/drive \
     --use-mmap \
     --allow-other \
     --user-agent=1000 \
     --dir-cache-time 1000h \
     --poll-interval 30s \
     --umask 002 \
     --cache-dir=/mnt/cache \
     --vfs-cache-mode full \
     --vfs-cache-max-size 250G \
     --vfs-cache-max-age 168h \
     --drive-chunk-size 128M"
    container_name: rclone
    devices:
      - /dev/fuse
    image: rclone/rclone
    networks:
      - default
    restart: unless-stopped
    security_opt:
      - apparmor:unconfined
    volumes:
      - ./config:/config
      - ./logs:/logs
      - /mnt/external/drive:/mnt/drive:shared
      - /mnt/external/temp:/mnt/cache

networks:
  default:
    name: media-server
