services:
  portainer:
    command: "-H unix:///var/run/docker.sock"
    container_name: portainer
    image: portainer/portainer-ce
    networks:
      - default
    ports:
      - "9000:9000"
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data

volumes:
  data:
    name: portainer

networks:
  default:
    name: portainer
